### ISSUE TITLE
Rotation: Add snap to 22.5° for curved train tracks?

### ISSUE THREAD

**Issue by kripton** [leozide/leocad#139]
Hi all, this is more a proposal or question than an actual bug:
The curved train tracks (2867) get a full circle with 16 pieces. So it's 360°/16=22.5° per curved track element. Wouldn't it be good it LeoCAD could also snap to that angle instead of 30°-steps? I tried adding that snap-angle myself but it would shift the keyboard shortcuts which might disturb some folks.
Related question: If I have two curved track elements, each rotated correctly (the first 0°, the other 22.5°), I'm not able to correctly "snap" them together. Is there an easy way to do so?
Thanks!

**Comment by leozide** [comment]
The preset angles were arbitrary and turned out to not be a good choice. It should include 22.5 because it's useful for the Technic connectors as well (112.5 and 157.5). Maybe the best way to handle this is to replace 180 with a custom setting where people can just enter the angle they want. Do you have any better ideas?

As for aligning tracks, you'll have to turn off snapping and move them to the right place.

**Comment by nathaneltitane** [comment]
I second this option!!! that angle setting is essential to all snapping hinge parts!
Thank you for implementing it: it would save the trouble of manually having to set it.

**Comment by kripton** [comment]
Oh, perfect, thanks for implementing it so fast!
