### ISSUE TITLE
"Rotation Snap > 1 Degree" is broken

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#296]
Steps are: 0, 3, 7, 10, 14, 18, 21, 25, 28, 32, 36, 39, 43, 46, 50, 54, 57, 61, 64, 68, 72, 75, 79, 82, 86, 90, ...

**Comment by leozide** [comment]
I don't understand this, can you explain when it's broken?

**Comment by Symbian9** [comment]
When I try rotate part with "1 Degree" snapping, each rotation step NOT equal 1 degree. 

Instead, every next rotation step is different and every next step is little bigger than previous.

Expected behaviour: every rotation step with "1 Degree" snapping should be really equal 1 degree.

**Comment by tcuje** [comment]
Same Issue here, my steps are 3.6, 7.2...

I debugged the app (master branch) and figured out, that the issue is related to the mouse sensitivity. As **workaround set your mouse sensitivity in the leocad preferences to minimal (leftmost) setting.**

I suggest we change the magic constants here (https://github.com/leozide/leocad/blob/51bf3d00780c2fab712d697ca8828792ae21b4f9/common/view.cpp#L3073) to a lower value, like 10 or so. I think the issue is related to modern computer mouses have much higher DPI, compared to older ones.

**Comment by Symbian9** [comment]
> As workaround set your mouse sensitivity in the LeoCAD preferences to minimal (leftmost) setting.

This workaround not help me. I still has steps as 1, 3, 5, 7, 10, ...
