### ISSUE TITLE
VR headset support?

### ISSUE THREAD

**Issue by robertleeplummerjr** [leozide/leocad#310]
I didn't see this issue either asked or answered so thought I'd start the conversation.  Is there plans or support for VR headset?  Would make for really neat eye candy.

**Comment by leozide** [comment]
There are no plans, it would be interesting but I don't own a headset.

**Comment by robertleeplummerjr** [comment]
If you were to be donated one, would it be something then planned?

**Comment by leozide** [comment]
I'm not sure, I got motion sickness pretty quickly last time I tried a VR headset so I may not be able to work on it at all.

I've never looked into VR development because of that, so I don't know what it takes to support different platforms and vendors. Let me ask a few friends who are into VR to see how complicated it is.

**Comment by robertleeplummerjr** [comment]
Ok. Answered sufficiently.  Ty.

**Comment by andybak** [comment]
I wonder if a simple viewer app could be built in Unity. Are there any docs for the LeoCAD file format?
