### ISSUE TITLE
Glitchy parts list whenever you open a saved project

### ISSUE THREAD

**Issue by TrevorThaManiac69** [leozide/leocad#33]
Icons for each Lego parts looks messed up when you open a saved project

**Comment by leozide** [comment]
It's working fine for me, can you post a screenshot?

Also, some more information about your system: What platform? Are you using a custom library or the default one? Did you compile your exe?

**Comment by TrevorThaManiac69** [comment]
Here.

![glitched](https://cloud.githubusercontent.com/assets/26022986/23640967/c23afd52-032b-11e7-9df7-6aa7068db12b.png)
![normal](https://cloud.githubusercontent.com/assets/26022986/23640969/c3bd1d86-032b-11e7-91ee-e7a838ffe6ce.png)

**Comment by TrevorThaManiac69** [comment]
I'm currently running Windows 7 Ultimate 32-bit.
I am using an default library.

**Comment by leozide** [comment]
I've tried to reproduce the bug but I can't get it to happen on any of the computers I tested, so I can only guess what's wrong.

If you select a different part category after the glitch happens, does it still look wrong?

Does the glitch happen if you select File->New instead of opening a file?

What video card do you have? If you're not sure you can just copy and paste the contents of the About Dialog here. Have you tried updating to the latest video card drivers?
