### ISSUE TITLE
LeoCAD not recognize "ldconfig.ldr" stored in same folder with "complete.zip"

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#359]
Version: `LeoCAD-Linux-50daa6a-x86_64.AppImage`

### Actual behavior

I just tried `LDConfig.ldr` UPDATE 2019-05-24 and UPDATE 2019-06-11.

If set *"Custom parts library"* as folder (e.i., `../ldraw`) and replace `../ldraw/LDconfig.ldr` file with custom `LDConfig.ldr` — LeoCAD recognize new colors.

![pic.1](https://i.imgur.com/yTqWAG0.png)

If set *"Custom parts library"* as ZIP and (e.i., `../complete.zip`) and add in same folder `ldrawunf.zip` + custom `ldconfig.ldr` (or `LDConfig.ldr`) - LeoCAD recognize `complete.zip` and `ldrawunf.zip`, BUT `ldconfig.ldr` NOT recognized!

![pic.2](https://i.imgur.com/FBPAhWN.png)

### Expected behavior

LeoCAD should recognize `ldconfig.ldr` (or `LDConfig.ldr`) placed in same folder where ZIP of *"Custom parts library"* stored.

- https://github.com/leozide/leocad/blob/master/common/lc_library.cpp#L319-L337

### REFERENCE

- https://forums.ldraw.org/thread-23434-post-32595.html#pid32595

**Comment by trevorsandy** [comment]
Couldn't you just put the ldconfig.ldr **in** the complete.zip as it would be when officially shipped ?

**Comment by Symbian9** [comment]
> Couldn't you just put the ldconfig.ldr in the complete.zip as it would be when officially shipped ?

This issue about importing custom `ldconfig.ldr` placed side-by-side with ZIP of "Custom parts library".

Main idea of this LeoCAD feature is set custom LDConfig from external file without need to merge it to ZIP.

**Comment by trevorsandy** [comment]
Understood. Indeed, this is a nice enhancement - particularly for building instructions. I did not well understand your main idea from the title of the ticket. My understanding was LeoCAD should recognize a custom LDConfig.ldr file if placed in the same directory as the complete.zip. 

I have already implemented this feature in the [LeoCAD library](https://github.com/trevorsandy/lpub3d/blob/6fb530970783a2d1cffe3c5bf658aa70c5b29c9d/lclib/common/lc_library.cpp#L318) bundled with LPub3D but instead of automatically, detecting the colour file in a specific location, the user must define the alternate colour file in the Preference settings, which also actively indicates that LeoCAD should use an alternate colour file.

Cheers,

**Comment by leozide** [comment]
I think there should be a configuration entry for both ldconfig.ldr and minifig.ini.

**Comment by Symbian9** [comment]
> there should be a configuration entry for both ldconfig.ldr and minifig.ini

Yeah. Add such fields in "Preferences" dialog, please.

**Comment by Symbian9** [comment]
Here is mockup of "Custom LDConfig.ldr" and "Custom MLCad.ini" fields for "Preferences" window

![pic.1](https://i.imgur.com/Dtxsqyc.png)
