### ISSUE TITLE
preview widget properties

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#513]
@leozide 
properties for the new preview widget are MIA in the preferences.
background color should match model space color by default unless otherwise specified

![Screenshot_20201011-203701_bVNC Free](https://user-images.githubusercontent.com/5674757/95694798-ddc35a00-0c01-11eb-974e-ef934f3f631e.jpg)

**Comment by trevorsandy** [comment]
> background color should match model space color by default unless otherwise specified

Indeed, this is the expected behavour as there is no user interface dialogue to change the background colour.

From my understanding, the default background type and colour, unless changed by a LeoCAD meta command is set by the following profile items, respectively: 

```c++
mBackgroundType = (lcBackgroundType)lcGetProfileInt(LC_PROFILE_DEFAULT_BACKGROUND_TYPE);
mBackgroundSolidColor = lcVector3FromColor(lcGetProfileInt(LC_PROFILE_DEFAULT_BACKGROUND_COLOR));
```
... and the default settings are as follows, respectively:

```c++
lcProfileEntry("Defaults", "BackgroundType", LC_BACKGROUND_SOLID),                        // LC_PROFILE_DEFAULT_BACKGROUND_TYPE
lcProfileEntry("Defaults", "BackgroundColor", LC_RGB(255, 255, 255)),                     // LC_PROFILE_DEFAULT_BACKGROUND_COLOR
```

This is why the preview background colour in your shot is white 255, 255, 255. What did you do to get the the main window display background to the colour it shows ? There is no preference setting to set background colour - you can see this is a TODO in the code [here](https://github.com/leozide/leocad/blob/28437d16f7347935cff65b9e827eb164d0f09217/common/lc_application.cpp#L116)

I did not implement a preference to change  the preview background colour because there is no preferences to change the background colour for the main window display.

Cheers,

**Comment by leozide** [comment]
It matches the main window background for me, as I think should be.

**Comment by nathaneltitane** [comment]
@trevorsandy @leozide probably due to the model preferences background (scene color) selection then - my apologies for the misunderstanding.

Will you be removing or changing this behavior as you mentioned a while ago?

**Comment by trevorsandy** [comment]
I expected the loaded model scene background settings to be inherited by the preview window just as they were inherited by the main window because the preview window uses the same preferences object/settings as the main window. 

I'll take a look.

Cheers,
