### ISSUE TITLE
ENHANCEMENT: use color widget as color selector for edit

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#561]
Having the color widget open helps in having a bigger palette tool available other than the one in the properties(which can be very small on higher dpi screens.

![Screenshot_20201219-184858_VNC Viewer](https://user-images.githubusercontent.com/5674757/102701962-ed2ad900-422a-11eb-8ebe-89b9f21c9a1d.png)

Can we use the color widget to modify part colors in the editor on the fly?

Usage:

1 - drop part in editor
2 - do edits and add more parts
3 - select one or more parts to change colors
4 - pick color directly from color widget

**Comment by leozide** [comment]
I don't really like this because it can lead to people changing the selection colors unintentionally.

I'm thinking of either painting the selection on double click or with a keyboard shortcut. 

I don't use a high dpi monitor so I didn't know the popup was too small, I'll increase the size.

**Comment by nathaneltitane** [comment]
> I don't really like this because it can lead to people changing the selection colors unintentionally.
> 
> I'm thinking of either painting the selection on double click or with a keyboard shortcut.
> 
> I don't use a high dpi monitor so I didn't know the popup was too small, I'll increase the size.

Maybe you could introduce a secondary mode, one that uses the color widget as main and the properties input as a secondary method (with specific selections)?

What I gather here is that the color widget doesn't seem to do much when it is present on the interface, other that picking the preview color for most part, when certain parts are tricky to identify.

I do recall, back when MLCAD was still the editor of choice (to some extent), the color picker would handle all the coloring/painting for any kind of selection (as long as it had to do with a part).

Also, thanks for looking into upping the properties color panel, I appreciate it.

**Comment by rsbx** [comment]
Please don't do something that requires MORE clicks to select a color or 
to "paint" a part or parts.

For reference: I use the color widget in the interface and tend to lock 
the preview color to the main color (a light yellow that shows the part 
details over the white background in the part selection widget) and 
select the color I want when inserting or painting a part. Other than 
the floating preview widget, I usually have only 1 leocad window, not a 
bunch of floating leocad widget windows.

It would be nice, however, if the _preview widget_ reflected the current 
selected color instead of the locked interface color.

When it comes to painting parts, 1) I'd like a way to paint all of the 
selects parts with a shortcut, and 2) a keyboard and/or mouse shortcut 
to paint the part under the pointer (even better if I can paint with 
more than 1 pre-selected color).

**Comment by rsbx** [comment]
Another thing that'd be nice is a large 'color swatch' at the top of the 
color widget to make it obvious what color(s) is currently selected. To 
make it quick to see what the current color is when the interface color 
is locked.

**Comment by nathaneltitane** [comment]
@leozide 
currently working on a model file any chance you could pump the color properties popup to be bigger?

**Comment by leozide** [comment]
@nathaneltitane are you overriding Qt high dpi settings with an env var? The popup is scaling for me.

**Comment by nathaneltitane** [comment]
Not that I know. Running a barebones ubuntu chrome with dwm on top.

**Comment by nathaneltitane** [comment]
@leozide is there a package or library you know of that i should install to supplement hidpi handling to my system?

**Comment by rsbx** [comment]
There might be useful some hints in the Arch Linux HiDPI page:
	https://wiki.archlinux.org/index.php/HiDPI

**Comment by nathaneltitane** [comment]
FYI @rsbx @leozide even while using a normally installed linux based system (ie: KDE Desktop via KUBUNTU) on my Surface Pro 3, I had the same issue where the properties color pop-up was not scaling.
I'll check if an env. variable needs to be set and if it changes anything...

**Comment by nathaneltitane** [comment]
The Overall interface size increases and scales when i call QT_DEVICE_PIXEL_RATIO=2

![Screenshot_20201229-150648_VNC Viewer.png](https://user-images.githubusercontent.com/5674757/103311151-94f09580-49e7-11eb-808d-09e61cf78d0c.png)

**Comment by leozide** [comment]
Looks like you don't have any scaling set on your display settings.

**Comment by nathaneltitane** [comment]
> Looks like you don't have any scaling set on your display settings.

Do explain? AS I mentioned prior, this is a barebones ubuntu base image 20.04.1 running in chroot atop Termux on Android. I run DWM with bare minimal dependencies and same goes for leocad.

**Comment by leozide** [comment]
I made some changes to make the popup wider but it's not supposed to scale just because you're using a high resolution monitor, if you want to make things scale then you should use your WM's display scale setting or the QT env var.

I also added a new button with shortcut support to paint the selection, see if that makes it easier to work.

**Comment by nathaneltitane** [comment]
As stated earlier, the QT env var did not change anything aside from the font dpi scaling - I appreciate it and this is already a good step forward.

Thanks!

**Comment by rsbx** [comment]
Nice! You implemented the color swatch on the color widget. But, it takes too much valuable vertical space on my (non hidpi) screen; forcing me to choose between smaller, harder to click colors, or making the part selector widget smaller and having to scroll even more to find the part I want.

My suggestion is to put the swatch between the 'Colors' label (which really isn't needed) and the control icons as a bar (instead of a square) without the color name. And have to color name and number only show on a hover. If you eliminate the 'Colors' label, the color swatch bar could be the entire width, minus the controls icons, making the currently select color readily apparent in the interface.

**Comment by rsbx** [comment]
Paint Select keyboard shortcut :+1: 
Paint mouse shortcut :+1:
