### ISSUE TITLE
Viewsphere disabled setting broken

### ISSUE THREAD

**Issue by trevorsandy** [leozide/leocad#584]
When the main view viewsphere is set to _Disabled_, in the Preferences dialogue, setting it to anything else is ignored so it is not possible to re-enable from Preferences. Additionally, it is also not possible to change display settings for the preview viewsphere.

Cheers,

**Comment by nathaneltitane** [comment]
@trevorsandy wasn't sure it was a bug at first - decided to wait on reporting it - guess it is!

@leozide setting is definitely ignored.

**Comment by trevorsandy** [comment]
Did you mean to remove the abilty to set the Preview _Size_, _Location_ and if _Floating_ or _Dockable_ ?

![Screenshot - 30_12_2020 , 20_11_42](https://user-images.githubusercontent.com/13388970/103375939-a4510b00-4adb-11eb-9dc9-0755cbd50131.png)

Cheers,

**Comment by leozide** [comment]
It was, I couldn't figure out a situation where the floating preview would be better than the dockable widget (I emailed you about it last week). Since there were some bugs left with it (app not closing, multiple previews, crashes) and I was changing this part of the code I decided to simplify things.

I don't mind bringing it back if there's a good use case for it though.

**Comment by trevorsandy** [comment]
Very well - no worries. Just checking to confirm.

Cheers,

**Comment by rsbx** [comment]
I prefer the floating widget since I can close the preview window to 
reclaim the screen space until I double click another part.

**Comment by leozide** [comment]
You can still float and close the preview widget.
