### ISSUE TITLE
PATCH: Improve normal weights

### ISSUE THREAD

**Issue by rsbx** [leozide/leocad#683]
[normalweight.patch.txt](https://github.com/leozide/leocad/files/6207252/normalweight.patch.txt)

**Comment by j6t** [comment]
A description of what the patch does would be appreciated. Please remember that the word "improve" does not carry information, because everybody will agree that a change will always improve the code base in some form, never disimprove it. Can you make your patch available in the form of a pull request or at least in a branch in a fork of this repository?

**Comment by rsbx** [comment]
Prior: each added normal to a vertex was given a wiegth of 1.0

After: each added normal to a vertex is given a weight proportional to the triangle it's associated angular coverage at that vertex.
