### ISSUE TITLE
ViewSphere corrupted when parts are selected from a loaded model

### ISSUE THREAD

**Issue by trevorsandy** [leozide/leocad#697]
**Describe the bug**
When one or move parts are selected from a loaded model, the view sphere becomes corrupted with artifacts.

**To Reproduce**
1. Open a model file
2. Select a part
3. Observe the ViewSphere
4. Click on an empty area of the view port
5. Observe the ViewSphere

**Expected behavior**
The ViewSphere should not be corrupted on part selection

**Screenshots**

Corrupted ViewShpere when part(s) selected:

![Screenshot - 16_04_2021 , 14_19_48](https://user-images.githubusercontent.com/13388970/115024184-07668200-9ec0-11eb-872f-40c55bec89a0.png)

ViewSphere restored after clicking on an empty area of the view port:

![Screenshot - 16_04_2021 , 14_19_30](https://user-images.githubusercontent.com/13388970/115024346-40065b80-9ec0-11eb-9e4c-928681994d37.png)

**Version**
 - OS: Windows 10
 - LeoCAD Version [compile from source at commit 278e953b819e0cf1e98f436369d438acda8e35bf]

**Additional context**
This behaviour is resolved when commit 278e953b819e0cf1e98f436369d438acda8e35bf is ommitted.

Cheers,

**Comment by rsbx** [comment]
Also happens on Debian 10 VM with https://github.com/leozide/leocad/commit/278e953b819e0cf1e98f436369d438acda8e35bf. I did not try with out that commit.

**Comment by nathaneltitane** [comment]
also happens when a model is being selected (win10 latest continuous build)
You can toggle in between selected/unselected and sphere comes an goes...

![image](https://user-images.githubusercontent.com/5674757/115081870-fa06c300-9ed2-11eb-85d6-22aebcdb42df.png)

![image](https://user-images.githubusercontent.com/5674757/115081885-fe32e080-9ed2-11eb-9283-f5c2b803513b.png)
