### ISSUE TITLE
no way to mouse click multiple selections (red)

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#931]
**Describe the bug**
The new properties widget and parts selection method does not allow for a quick selectin and modification of all selected parts - it only changes the part in blue.

**To Reproduce**
1 - open model
2 - selct pieces (ctrl + click)
3 - go to parts properties and select desired entry for change
4 - only pert in blue gets modified.

**Expected behavior**
old behavior automatically defaulted to 'multiple parts selected' and thus, permitted a quick modification of the desired part or group of parts to the new selection.

**Screenshots**
![image](https://github.com/user-attachments/assets/99a09f26-f65b-4bca-8590-ef0ac5040050)

![image](https://github.com/user-attachments/assets/226dd5b5-a526-4226-8a02-3b7ba9ca3e36)

**Version (please complete the following information):**
continuous

**Crash information:**
n/a

**Additional context**
alternatively: propose a user defined option to revert back to old behavior or add a way to <modifier> click to keep selection red on all parts (the same way a rectangular lasso selection would) to discreetly select components to change.

**Comment by app4soft** [comment]
>  I am simply highlighting teh fact that there is no alternate method for selection types using mouse + keyboard modifier to explicitly select discreet parts

I'm not sure I fully understand actual issue, but here is what I'm observing with latest LeoCAD build:

### Selection:

1. with selection rectangle lasso — selects all parts, without activating last selected part (all "red", no "blue")
2. select with <kbd>LMB</kbd>+<kbd>Ctrl</kbd> by...
2.1. ... lasso rectangle all — selectes selects all parts, without activating last selected part (all in "red").
2.2. ... lasso one-by-one — same as previos.
2.3. ... click one-by-one — selects all selected parts, and keeps last selected part active (in "blue").

Note, that <kbd>LMB</kbd>+<kbd>Ctrl</kbd> shortcut click works as expected for inactivate last selected part, and <kbd>LMB</kbd>+<kbd>Shift</kbd> shortcut works as expected for exclude part from selection as well.)

### Property changing

1. If there is no "blue" part among "reds":
1.1. gizmo is moving to the center of gravity (CoG) of all selected parts;
1.2. its impossible to move parts — LeoCAD ignores manual value input for properties of gizmo (sitting in CoG);
1.3. its possible to move all the selected parts with moving gizmo by mouse;
1.4. its possible to move all the selected parts wit arrows keys.
2. If there is "blue" among "reds":
2.1. gizmo moving to origin of "blue" parts;
2.2. its possible to move all the selected parts changing propertis of "blue" (last active among "reds");
2.3. its possible to move all the selected parts with moving gizmo by mouse.
2.4. its possible to move all the selected parts wit arrows keys.

### Feature or Bug?

So, as I understand, the fact that "Properties" widget is ignoring manual value input for gizmo properties if there is no active last selected ("blue") part looks like a bug (or is it a feature?).

BTW, for moving all the parts all together its really good practice to select one part (actiate to set it "blue") among other selected ("reds") and manually input news XYZ values for this reference part to move all the parts accordingly (as in most cases it last selected part would has integer values for XYZ, instead of gizmo placed in CoG, which XYZ values in most cases are decimal fractions, because its calculated and approximted from many parts origins XYZ positins).

@nathaneltitane, Is it what actual issue report is about? Or am I missing something?

**Comment by nathaneltitane** [comment]
it has nothing to do with rotation or translation - it was merely about changing the part to another while disreetly slecting parts manually from withing a complex assembly or submodel.

i do not want to 'lasso all' or 'lasso some parts' i want to mod+click the parts i need to change and for them to all remain red after selection so that the properties widget remains on 'multiple selection' to change all parts, not just the last selected/blue one.

**Comment by app4soft** [comment]
> i do not want to 'lasso all' or 'lasso some parts' i want to mod+click the parts i need to change and for them to all remain red after selection so that the properties widget remains on 'multiple selection' to change all parts, not just the last selected/blue one.

Ok, so its much simpler task, and here is the 4th method supported by LeoCAD, to solve your task:

1. Hold <kbd>Ctrl</kbd> and start selecting parts by <kbd>LMB</kbd> clicks one-by-one, and for the last one part use a double-click — now all selected parts should be "red";
  (NOTE: <kbd>Ctrl</kbd>+<kbd>LMB</kbd> double-click on last selecting part (or just one extra <kbd>Ctrl</kbd>+<kbd>LMB</kbd> click on "blue") deactivates last selected part, but keeps it selected as "red")
3. Go to "Properties" widget and  select "Part" to replace with;
4. Done.

So, there is no LeoCAD issue at all.

Its all about missing docs describing all this selection methods.

Regards.

**Comment by nathaneltitane** [comment]
> > i do not want to 'lasso all' or 'lasso some parts' i want to mod+click the parts i need to change and for them to all remain red after selection so that the properties widget remains on 'multiple selection' to change all parts, not just the last selected/blue one.
> 
> Ok, so its much simpler task, and here is the ~4th~ 6th method (see update: [#931 (comment)](https://github.com/leozide/leocad/issues/931#issuecomment-2389543841)) supported by LeoCAD, to solve your task:
> 
> 1. Hold Ctrl and start selecting parts by LMB clicks one-by-one, and for the last one part use a double-click — now all selected parts should be "red";
>    (NOTE: Ctrl+LMB double-click on last selecting part (or just one extra Ctrl+LMB click on "blue") deactivates last selected part, but keeps it selected as "red")
> 2. Go to "Properties" widget and  select "Part" to replace with;
> 3. Done.
> 
> So, there is no LeoCAD issue at all.
> 
> Its all about missing docs describing all this selection methods.
> 
> Regards.

the double click on last was not intuitive at all - your suggestion does work - would still be good to have options in the keyboard preferences

**Comment by leozide** [comment]
Should be fixed, it was a bug that you needed a blue part to change properties

**Comment by app4soft** [comment]
@leozide, It might be good to has an extra option choose default mode:

* View
  * Preferences
    * General
      * `[ ]` Keep the last selected part in focus (for multiply selection)

Turned Off by default.

**Comment by nathaneltitane** [comment]
> Should be fixed, it was a bug that you needed a blue part to change properties

ok @leozide, yet, to be fair, this is now adding a click to the selection to ensure that the multiple selection changes are done correctly by deselecting the blue part to make all parts change....

can there be some option to toggle it on or off?

**Comment by nathaneltitane** [comment]
> > Should be fixed, it was a bug that you needed a blue part to change properties
> 
> ok @leozide, yet, to be fair, this is now adding a click to the selection to ensure that the multiple selection changes are done correctly by deselecting the blue part to make all parts change....
> 
> can there be some option to toggle it on or off?

Additionally @leozide  - would it also be possible to add an option to enable single click selection - that'S also an additional click towards the parts widget selection that is yet another annoyance and may be something that is left to personal user preference?

**Comment by nathaneltitane** [comment]
@leozide this issue seems to have many other implications in the addition of several mouse clicks or mouse + modifier clicks to achieve what used to be a simple click, toggle, apply 

if one is to, for instance, select all parts by color, that first selection remains blue.
attempting to apply the new color to that selection group now leaves the remainder of the red parts unchanged unless a ctrl + click is done to toggle the 'multiple selection' on the widget to have alll selected parts change....

![image](https://github.com/user-attachments/assets/4dc53a32-3c35-4e5b-95e3-90f9fd36d399)

apply color filter and select a part

![image](https://github.com/user-attachments/assets/4b811fe4-08d4-4dfa-90f6-d149e66a13c6)

result:

![image](https://github.com/user-attachments/assets/8d6b1c56-8b9e-4162-ba45-e3eab3b4ea2f)


when in older versions result would have been

![image](https://github.com/user-attachments/assets/5e01f75c-15e0-4b6c-a3db-5180a59419ac)


what was a 'bug' seems to not have been tracked early enough and now the 'fix' is turning to be quite the cumbersome and clunky aspect of what was a streamlined and efficient workflow.

and to boot, most distributions are not shipping leocad to it'S latest continuous feature set - there will be an onslaught of complaints in the near future when leocad is packaged to include these changes...
